[xray]
src.github = "XTLS/Xray-core"
fetch.github = "XTLS/Xray-core"

[v2fly-geoip]
src.github = "v2fly/geoip"
fetch.url = "https://github.com/v2fly/geoip/releases/download/$ver/geoip.dat"

[v2fly-private]
src.github = "v2fly/geoip"
fetch.url = "https://github.com/v2fly/geoip/releases/download/$ver/private.dat"

[v2fly-geosite]
src.github = "v2fly/domain-list-community"
fetch.url = "https://github.com/v2fly/domain-list-community/releases/download/$ver/dlc.dat"

[icalingua-plus-plus]
src.github = "Icalingua-plus-plus/Icalingua-plus-plus"
fetch.github = "Icalingua-plus-plus/Icalingua-plus-plus"

[icalingua-plus-plus-aur]
src.git = "https://aur.archlinux.org/icalingua++.git"
fetch.git = "https://aur.archlinux.org/icalingua++.git"

[git-qq]
src.github = "lomirus/gtk-qq"
fetch.github = "lomirus/gtk-qq"

[river-git]
src.git = "https://github.com/riverwm/river"
fetch.git = "https://github.com/riverwm/river"
